/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Calc;

/**
 *
 * @author erikl
 */
public class Jv extends javax.swing.JFrame {

    /**
     * Creates new form Jv
     */
    public Jv() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jCheckBox1 = new javax.swing.JCheckBox();
        txtN1 = new javax.swing.JTextField();
        txtN2 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        opSimb = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        opSoma = new javax.swing.JButton();
        opSub = new javax.swing.JButton();
        opMulti = new javax.swing.JButton();
        opDiv = new javax.swing.JButton();
        opRdiv = new javax.swing.JButton();
        res = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        jCheckBox1.setText("jCheckBox1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        opSimb.setText("#");
        opSimb.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                opSimbAncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });

        jLabel4.setText("=");

        opSoma.setText("+");
        opSoma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opSomaActionPerformed(evt);
            }
        });

        opSub.setText("-");
        opSub.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opSubActionPerformed(evt);
            }
        });

        opMulti.setText("*");
        opMulti.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opMultiActionPerformed(evt);
            }
        });

        opDiv.setText("/");
        opDiv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opDivActionPerformed(evt);
            }
        });

        opRdiv.setText("%");
        opRdiv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opRdivActionPerformed(evt);
            }
        });

        res.setText("0");

        jLabel6.setText("CALCULADORA");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(51, 51, 51)
                        .addComponent(opSoma)
                        .addGap(18, 18, 18)
                        .addComponent(opSub)
                        .addGap(18, 18, 18)
                        .addComponent(opMulti)
                        .addGap(18, 18, 18)
                        .addComponent(opDiv)
                        .addGap(18, 18, 18)
                        .addComponent(opRdiv))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(67, 67, 67)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtN1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                        .addComponent(opSimb, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtN2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(42, 42, 42)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(res, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(167, 167, 167)
                        .addComponent(jLabel6)))
                .addContainerGap(81, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6)
                .addGap(49, 49, 49)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtN1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(opSimb)
                        .addComponent(jLabel4)
                        .addComponent(res))
                    .addComponent(txtN2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(opSoma)
                    .addComponent(opSub)
                    .addComponent(opMulti)
                    .addComponent(opDiv)
                    .addComponent(opRdiv))
                .addContainerGap(148, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void opMultiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opMultiActionPerformed
        // TODO add your handling code here:
        opSimb.setText("*");
        int multn1 = Integer.parseInt(txtN1.getText());
        int multn2 = Integer.parseInt(txtN2.getText());
        int multRes = multn1 * multn2;
        
        res.setText(Integer.toString(multRes));
    }//GEN-LAST:event_opMultiActionPerformed

    private void opDivActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opDivActionPerformed
        // TODO add your handling code here:
        opSimb.setText("/");
        float divn1 = Float.parseFloat(txtN1.getText());
        float divn2 = Float.parseFloat(txtN2.getText());
        float divRes = divn1 / divn2;
        
        res.setText(Float.toString(divRes));
    }//GEN-LAST:event_opDivActionPerformed

    private void opRdivActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opRdivActionPerformed
        // TODO add your handling code here:
         opSimb.setText("%");
        float rdivn1 = Float.parseFloat(txtN1.getText());
        float rdivn2 = Float.parseFloat(txtN2.getText());
        float rdivRes = rdivn1 % rdivn2;
        
        res.setText(Float.toString(rdivRes));
    }//GEN-LAST:event_opRdivActionPerformed

    private void opSomaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opSomaActionPerformed
        // TODO add your handling code here:
        opSimb.setText("+");
        int sn1 = Integer.parseInt(txtN1.getText());
        int sn2 = Integer.parseInt(txtN2.getText());
        int sRes = sn1 + sn2;
        
        res.setText(Integer.toString(sRes));
        
        
        
    }//GEN-LAST:event_opSomaActionPerformed

    private void opSimbAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_opSimbAncestorAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_opSimbAncestorAdded

    private void opSubActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opSubActionPerformed
        // TODO add your handling code here:
        opSimb.setText("-");
        int subn1 = Integer.parseInt(txtN1.getText());
        int subn2 = Integer.parseInt(txtN2.getText());
        int subRes = subn1 - subn2;
        
        res.setText(Integer.toString(subRes));
        
    }//GEN-LAST:event_opSubActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Jv.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Jv.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Jv.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Jv.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Jv().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JButton opDiv;
    private javax.swing.JButton opMulti;
    private javax.swing.JButton opRdiv;
    private javax.swing.JLabel opSimb;
    private javax.swing.JButton opSoma;
    private javax.swing.JButton opSub;
    private javax.swing.JLabel res;
    private javax.swing.JTextField txtN1;
    private javax.swing.JTextField txtN2;
    // End of variables declaration//GEN-END:variables
}
